-- FactionIDs.lua -- baked faction NAME -> Blizzard factionID lookup.
--
-- WHY: the Faction tab groups quests by reputation-faction NAME, but the live
-- reputation API (C_Reputation / C_MajorFactions) is ID-based. A runtime index
-- scan only sees factions under EXPANDED reputation headers, so it misses most
-- classic factions. This static table -- generated from the first-party Blizzard
-- Game Data quest-reward cache (rewards.reputations[].reward.{name,id}) -- lets
-- the reputation bar resolve any faction we group on without that hack.
--
-- Covers every faction our catalog rewards (86 factions). Regenerate from
-- the _generator quest cache if the catalog gains new reputation factions.
local _, DT = ...

DT.FactionIDs = {
    ["Argent Crusade"] = 1106,
    ["Baradin's Wardens"] = 1177,
    ["Booty Bay"] = 21,
    ["Cenarion Expedition"] = 942,
    ["Chee Chee"] = 1277,
    ["Court of Night"] = 2464,
    ["Dark Talons"] = 2523,
    ["Darkmoon Faire"] = 909,
    ["Darnassus"] = 69,
    ["Death's Advance"] = 2470,
    ["Dominance Offensive"] = 1375,
    ["Dragonmaw Clan"] = 1172,
    ["Dragonscale Expedition"] = 2507,
    ["Ella"] = 1275,
    ["Emperor Shaohao"] = 1492,
    ["Explorers' League"] = 1068,
    ["Farmer Fung"] = 1283,
    ["Fish Fellreed"] = 1282,
    ["Frenzyheart Tribe"] = 1104,
    ["Gina Mudclaw"] = 1281,
    ["Glimmerogg Racer"] = 2568,
    ["Golden Lotus"] = 1269,
    ["Guardians of Hyjal"] = 1158,
    ["Hand of the Prophet"] = 1847,
    ["Haohan Mudclaw"] = 1279,
    ["Hellscream's Reach"] = 1178,
    ["Honor Hold"] = 946,
    ["Horde Expedition"] = 1052,
    ["Ironforge"] = 47,
    ["Iskaara Tuskarr"] = 2511,
    ["Jogu the Drunk"] = 1273,
    ["Keepers of Time"] = 989,
    ["Kirin Tor"] = 1090,
    ["Kirin Tor Offensive"] = 1387,
    ["Knights of the Ebon Blade"] = 1098,
    ["Kurenai"] = 978,
    ["Lower City"] = 1011,
    ["Maruuk Centaur"] = 2503,
    ["Nat Pagle"] = 1358,
    ["Netherwing"] = 1015,
    ["Obsidian Warders"] = 2524,
    ["Ogri'la"] = 1038,
    ["Old Hillpaw"] = 1276,
    ["Operation: Shieldwall"] = 1376,
    ["Order of the Awakened"] = 1849,
    ["Order of the Cloud Serpent"] = 1271,
    ["Orgrimmar"] = 76,
    ["Ramkahen"] = 1173,
    ["Rustbolt Resistance"] = 2391,
    ["Sabellian"] = 2518,
    ["Sha'tari Skyguard"] = 1031,
    ["Shado-Pan"] = 1270,
    ["Shattered Sun Offensive"] = 1077,
    ["Sho"] = 1278,
    ["Steamwheedle Preservation Society"] = 1711,
    ["Stormwind"] = 72,
    ["Sunreaver Onslaught"] = 1388,
    ["The Anglers"] = 1302,
    ["The August Celestials"] = 1341,
    ["The Consortium"] = 933,
    ["The Frostborn"] = 1126,
    ["The Kalu'ak"] = 1073,
    ["The Klaxxi"] = 1337,
    ["The Mag'har"] = 941,
    ["The Oracles"] = 1105,
    ["The Saberstalkers"] = 1850,
    ["The Sha'tar"] = 935,
    ["The Silver Covenant"] = 1094,
    ["The Sons of Hodir"] = 1119,
    ["The Sunreavers"] = 1124,
    ["The Tillers"] = 1272,
    ["The Undying Army"] = 2410,
    ["The Wyrmrest Accord"] = 1091,
    ["Therazane"] = 1171,
    ["Thrallmar"] = 947,
    ["Thunder Bluff"] = 81,
    ["Tina Mudclaw"] = 1280,
    ["Undercity"] = 68,
    ["Valdrakken Accord"] = 2510,
    ["Valiance Expedition"] = 1050,
    ["Ve'nari"] = 2432,
    ["Vol'jin's Headhunters"] = 1848,
    ["Warsong Offensive"] = 1085,
    ["Wildhammer Clan"] = 1174,
    ["Wintersaber Trainers"] = 589,
    ["Wrathion"] = 2517,
}
